# Generated by Django 3.1.3 on 2020-11-16 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='SOME STRING', max_length=150)),
                ('first_name', models.CharField(blank=True, default='SOME STRING', max_length=200)),
                ('last_name', models.CharField(blank=True, default='SOME STRING', max_length=200)),
                ('email', models.CharField(blank=True, default='SOME STRING', max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
